name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || echo "No linting configured"
    
    - name: Run tests
      run: npm test || echo "No tests configured"
    
    - name: Build
      run: npm run build --if-present
    
    - name: CDK synth
      run: npx cdk synth
      env:
        AWS_REGION: us-east-1
        # Use mock credentials for CI environment
        AWS_ACCESS_KEY_ID: mock
        AWS_SECRET_ACCESS_KEY: mock

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security scan
      run: |
        npm install -g @cyclonedx/bom
        cyclonedx-bom -o bom.xml
        
    - name: Upload BOM
      uses: actions/upload-artifact@v3
      with:
        name: bom
        path: bom.xml
